config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  authenticated :user do
    root to: "dashboard#show", as: :authenticated_root
  end

  resources :users do
    resources :wallet_addresses, only: %i[new create] do
      get :info, on: :collection
    end
  end
  resources :payments, only: %i[new create]
  resources :expenses, only: %i[new create]
  resources :friendships, only: %i[new create]
  resource :dashboard, only: :show
  get :homepage, to: "pages#show"

  root to: "pages#show"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :entered_expenses, class_name: "Expense", foreign_key: :creator_id
  has_many :expenses, class_name: "Expense", foreign_key: :payer_id
  has_many :debts
  has_many :friendships_as_primary, class_name: "Friendship", foreign_key: "primary_id", dependent: :destroy
  has_many :friendships_as_secondary, class_name: "Friendship", foreign_key: "secondary_id", dependent: :destroy
  has_many :wallet_addresses, dependent: :destroy

  has_many :owed_expenses, through: :debts, source: :expense

  has_one :default_address, -> { where(is_default: true) }, class_name: "WalletAddress"

  before_save do
    self.avatar_url ||= "https://testing-cdn.spark.re/uploads/material/upload/4ab581955f989e8f335f56fd34dd4a5c/Untitled_design__3_.png"
  end

  def name
    [first_name, last_name].join(" ")
  end

  def to_s
    name
  end

  def friendships
    Friendship.by_user(id)
  end

  def friendship_with(user_id)
    friendships.by_user(user_id).first
  end

  def friends
    secondary_ids = friendships_as_primary.pluck(:secondary_id)
    primary_ids = friendships_as_secondary.pluck(:primary_id)
    User.where(id: [secondary_ids, primary_ids, id].flatten)
  end

  def involved_expenses
    (expenses + owed_expenses).uniq
  end

  def net_balance
    expenses.sum(:amount) - debts.sum(:amount)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController< ApplicationController
  def show
  end
end

app/views/users/show.html.haml
.row.app-content
  .col-3
    = render "layouts/user_sidebar"
  .col-6.no-padding
    .header
      %h3 Your Account

    .container.no-padding#account
      .pad-content
        .row
          .col-6
            %strong Email
            %p= current_user.email
          .col-6
            %strong Member since
            %p= current_user.created_at.to_date
        %br
        .row
          .col-12.wallets-header
            %h4 Wallet Addresses
            = link_to info_user_wallet_addresses_path(current_user), remote: true, "data-toggle" => "modal", "data-target" => "#wallet-info", class: "btn btn-outline-info" do
              %span About
            #wallet-info.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog"}
              .modal-dialog{:role => "document"}
                .modal-content
            %hr
          .col-12
            - if current_user.wallet_addresses.any?
              .addresses
                - current_user.wallet_addresses.each do |wa|
                  = wa.address
                  - if wa.is_default
                    %em (Default)
            - else
              .text-center
                %p You haven't registered any wallet addresses yet.
                %p Register one now to make it easier for your friends to deposit payments for you!

            .text-center
              = link_to "Register an Address", new_user_wallet_address_path(current_user), remote: true, "data-toggle" => "modal", "data-target" => "#modal-window", class: "btn btn-success"
            #modal-window.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog"}
              .modal-dialog{:role => "document"}
                .modal-content

  .col-3
    = render "layouts/friends_sidebar"