config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  authenticated :user do
    root to: "dashboard#show", as: :authenticated_root
  end

  resources :users do
    resources :wallet_addresses, only: %i[new create] do
      get :info, on: :collection
    end
  end
  resources :payments, only: %i[new create]
  resources :expenses, only: %i[new create]
  resources :friendships, only: %i[new create]
  resource :dashboard, only: :show
  get :homepage, to: "pages#show"

  root to: "pages#show"
end

app/views/balances/_index.html.haml
.col-6.no-padding
  .header
    %h3 Balances

  #modal-window.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog"}
    .modal-dialog{:role => "document"}
      .modal-content

  .container.no-padding
    .pad-content
      .col-12.text-center
        %h5 Funds available to withdraw
        - if defined?(@balance_in_cad) && @balance_in_eth > 0
          %h3
            .green $#{format("%.2f", @balance_in_cad)} CAD
          %h4
            %em.grey ETH #{@balance_in_eth}
          %button.btn.btn-success#withdraw Withdraw Funds
        - else
          %h3
            .grey $0.00 CAD
          %h4
            %em.grey ETH 0
          - if !current_user.default_address
            %p
              %em You haven't set up a digital wallet address yet!
            = link_to "Find out more", info_user_wallet_addresses_path(current_user), remote: true, "data-toggle" => "modal", "data-target" => "#wallet-info", class: "btn btn-info"
            #wallet-info.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog"}
              .modal-dialog{:role => "document"}
                .modal-content

    - if current_user.friendships.any?
      %table.table.payments-list
        %tbody
          - current_user.friendships.each do |friendship|
            %tr
              - if current_user == friendship.primary
                %td
                  %strong= friendship.secondary
                %td
                  %em.small You owe
                  - if friendship.primary_owes <= 0.0
                    %h5.grey $0.00
                  - else
                    %h5.red $#{format("%.2f", friendship.primary_owes)}
                %td.you-owe
                  %em.small They owe
                  - if friendship.secondary_owes <= 0.0
                    %h5.grey $0.00
                  - else
                    %h5.green $#{format("%.2f", friendship.secondary_owes)}
                %td.settle-up
                  = link_to "Settle Up", new_payment_path(user_id: friendship.secondary_id), remote: true, "data-toggle" => "modal", "data-target" => "#modal-window", class: "btn btn-info settle-up"
              - else
                %td
                  %strong= friendship.primary
                %td
                  %em.small You owe
                  - if friendship.secondary_owes <= 0.0
                    %h5.grey $0.00
                  - else
                    %h5.red $#{format("%.2f", friendship.secondary_owes)}
                %td.you-owe
                  %em.small They owe
                  - if friendship.primary_owes <= 0.0
                    %h5.grey $0.00
                  - else
                    %h5.green $#{format("%.2f", friendship.primary_owes)}
                %td.settle-up
                  = link_to "Settle Up", new_payment_path(user_id: friendship.primary_id), remote: true, "data-toggle" => "modal", "data-target" => "#modal-window", class: "btn btn-info settle-up"