config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  authenticated :user do
    root to: "dashboard#show", as: :authenticated_root
  end

  resources :users do
    resources :wallet_addresses, only: %i[new create] do
      get :info, on: :collection
    end
  end
  resources :payments, only: %i[new create]
  resources :expenses, only: %i[new create]
  resources :friendships, only: %i[new create]
  resource :dashboard, only: :show
  get :homepage, to: "pages#show"

  root to: "pages#show"
end

app/models/payment.rb
class Payment < ApplicationRecord
  CURRENCIES = %w[CAD].freeze

  belongs_to :creator, class_name: "User"
  belongs_to :payer, class_name: "User"
  has_many :debts

  def to_s
    description
  end

  def debtor_ids
    debts.pluck(:user_id)
  end

  def debtor_ids=(str)
    ids = str.split(",")
    ids.each { |uid| debts.find_or_initialize_by(user_id: uid) }
  end
end

app/controllers/payments_controller.rb
# frozen_string_literal: true

class PaymentsController< ApplicationController
  before_action :authenticate_user!
  before_action :set_payee, only: :new

  def new
    @payment = current_user.expenses.build(kind: "payment", creator: current_user)
  end

  def create
    @payment = current_user.expenses.build(kind: "payment", creator: current_user)
    @payment.update(payment_params)
    redirect_back fallback_location: dashboard_path(display: "balances"), flash: { success: "Payment recorded" }
  end

  private

  def payment_params
    params.require(:expense).permit(:payment_kind, :amount, debtor_ids: [])
  end

  def set_payee
    @friendship = current_user.friendship_with(params[:user_id])
    @payee = @friendship.friend_to(current_user)
  end
end

app/views/payments/_new.html.haml
= form_for @payment, url: payments_path, html: {id: "payments_form"} do |f|
  .modal-header
    %h4#myModalLabel.modal-title Settle up with #{@payee}
    %button.close{"data-dismiss" => "modal", :type => "button"} x
  .modal-body
    = devise_error_messages!
    - if @payee.default_address.present?
      #payee-address{"data-address" => @payee.default_address.address}
      .form-group
        = f.label :payment_kind
        = f.select :payment_kind, [["Record a payment", "paid"], ["Send ether", "deposited"]], { include_blank: false }, {class: "form-control" }
    - else
      = f.hidden_field :payment_kind, value: "paid"
    .form-group
      = f.label :amount, "Amount in CAD"
      = f.number_field :amount, value: [@friendship.balance_of(current_user), 0.0].max, min: 0.0, step: 0.01, required: true, class: "form-control"

    = f.hidden_field :debtor_ids, value: @payee.id, multiple: true

  .modal-footer
    %button.btn.btn-primary#pay_button Save

app/views/payments/new.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'new') %>");
$("#modal-window").modal();