config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  authenticated :user do
    root to: "dashboard#show", as: :authenticated_root
  end

  resources :users do
    resources :wallet_addresses, only: %i[new create] do
      get :info, on: :collection
    end
  end
  resources :payments, only: %i[new create]
  resources :expenses, only: %i[new create]
  resources :friendships, only: %i[new create]
  resource :dashboard, only: :show
  get :homepage, to: "pages#show"

  root to: "pages#show"
end

app/views/layouts/_friends_sidebar.html.haml
.container
  %h4.pad-top Friends
  %hr
  - if current_user.friendships.any?
    %table
      %tbody
        - current_user.friendships.each do |f|
          %tr
            %td
              .circle
            %td
              %em= f.friend_to(current_user)
  - else
    %p
      %em You have no friends :(

  %hr
  .container.no-padding.text-center
    = link_to "Add Friend", new_friendship_path, remote: true, "data-toggle" => "modal", "data-target" => "#modal-window", class: "btn btn-outline-success"
    #friendship-window.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog"}
      .modal-dialog{:role => "document"}
        .modal-content

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-md.navbar-dark.bg-dark.mb-4
  %a.navbar-brand{:href => homepage_path} CRYPTWISE
  %button.navbar-toggler{"aria-controls" => "navbarCollapse", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarCollapse", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarCollapse.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      - if current_user
        %li.nav-item{class: ("active" if controller_name == "dashboard")}
          %a.nav-link{href: root_path}
            Dashboard
            %span.sr-only (current)
        %li.nav-item{class: ("active" unless controller_name == "dashboard")}
          %a.nav-link{href: user_path(current_user)} Account
    - if current_user
      = link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-outline-success"
    - else
      = link_to "Sign In", user_session_path, class: "btn btn-outline-success"

app/views/layouts/_user_sidebar.html.haml
.container.text-center
  %img.rounded-circle.avatar{src: current_user.avatar_url}
  %h3= current_user

  %span
    %span Your net balance is
  - if current_user.net_balance < 0
    %h3.red $#{format("%.2f", current_user.net_balance.abs)} CAD
  - else
    %h3.green $#{format("%.2f", current_user.net_balance)} CAD
  %span
    Total paid:
    %span
      %strong $#{format("%.2f", current_user.expenses.sum(:amount))}
  %br
  %span
    Total owed:
    %span
      %strong $#{format("%.2f", current_user.debts.sum(:amount))}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Cryptwise
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    %link{crossorigin: "anonymous", href: "https://use.fontawesome.com/releases/v5.5.0/css/all.css", integrity: "sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU", rel: "stylesheet"}/

  %body
    = render "layouts/navbar"
    = yield
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'